### ISSUE TITLE
Doesn't generate getters

### ISSUE THREAD

**Issue by TheLastGimbus** [7mada123/isolate_generator#1]
Hi there!

OMG i love this so repo so much!! Recenlty i've been scrathing my head on how to move logic from main ui to https://pub.dev/packages/flutter_foreground_task - i was crying that i can't use all my beautiful classes with their streams, but now i can!

By the way - this will require me to pass an isolate name/send port/whatever *from* the `foreground_task`s isolate to the main isolate, on the fly - could this be possible with your generator? For now i see that it only allows me to get a class that creates it's own isolate - but i cannot "join" one/pass a reference to it somewhere else :thinking: 

Coming back to the issue: i have a class like this

```dart
class Headphones {
  ...
  Stream<HeadphonesBatteryData> get batteryData => ...;
  Stream<HeadphonesAncMode> get ancMode => ...;
  Future<void> setAncMode(newAncMode) => ...;
}
```

And the generator gives me:
```
class HeadphonesIsolate {
  ...
  Future<void> setAncMode(newAncMode => ...;
  // no stream :(((
}
```

I think i identified why:

https://github.com/7mada123/isolate_generator/blob/54d0142c941003bbfbd9644b4e0a4b4b1fd18469/lib/isolate_wraper_class.dart#L90

You just get the `classElement.methods` - no getters/setters - "accessors" - https://pub.dev/documentation/analyzer/latest/dart_element_element/InterfaceOrAugmentationElement/accessors.html

Both accesors and methods implement the [`ExecutableElement`](https://pub.dev/documentation/analyzer/latest/dart_element_element/ExecutableElement-class.html) - so maybe we can just boil them down to those?

**Comment by 7mada123** [comment]
Hi Mateusz, thank you for your feedback.

You are correct, the package currently only support methods,
If your class look like :
```
class Headphones {
  ...
  Stream<HeadphonesBatteryData> batteryData() => ...;
  Stream<HeadphonesAncMode> ancMode() => ...;
  Future<void> setAncMode(newAncMode) => ...;
}
```
The generated class will have `batteryData` and `ancMode` also. I am planning to add getter support but it will only be for streams since isolate communication happen asynchronously.

**Comment by TheLastGimbus** [comment]
Um, i don't know where is a problem - can we await the getter?

```dart
int get number;
// into ->
Future<int> get number

final n = await myClass.number;
```

**Comment by 7mada123** [comment]
Very interesting, I haven't thought about using getters asynchronously before.
Another issue is that getters should be updated automatically, what can we do here?

**Comment by TheLastGimbus** [comment]
> Another issue is that getters should be updated automatically

What do you mean?

**Comment by 7mada123** [comment]
How can we handle getters in the isolate, an expected behaviour when using getter is that it's value should be updated automatically.
Honestly I can't think of a way now

**Comment by TheLastGimbus** [comment]
What? 🤨 Getter is like completely normal function, just without the `()`. Literally

Setter is the same as you would call `setX(newX) => _x = newX`

They don't have any different behaviour, just syntax

**Comment by 7mada123** [comment]
lol so true, I will merging your pull request now and do some modification later
